name=Automatic Stamper
version=1.0.0
author=Isaac Boyd <isaacjonthanboyd@gmail.com>
maintainer=Isaac Boyd <isaacjonthanboyd@gmail.com>
sentence=This is a library for my Automatic Stamper.
paragraph=This is a library for my Automatic Stamper.
category=stamps
url=https://github.com/isaac-boyd/Automatic_Stamper/
architectures=*
